GreenConscious/About/urls.py
from django.urls import path
from .views import about_view

urlpatterns = [
    path('', about_view, name='about'),
]

GreenConscious/GreenConscious/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# Define URL patterns for each app
greenconscious_patterns = [
    path('', include('Login_SignUp.urls')),
    path('', include('MainPage.urls')),
    path('events/', include('EventsPage.urls')),
    path('community/', include('community.urls')),
    path('volunteer_matching/', include('VolunteerMatching.urls')),
    path('about/', include('About.urls')),
    path('contact/', include('Contact.urls')),
    path('', include('userhistory.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('greenconscious/', include(greenconscious_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GreenConscious/Login_SignUp/urls.py
from django.urls import path
from . import views

app_name = 'Login_SignUp'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('login/', views.loginPage,  name='loginPage'),
    path('logout/', views.logoutPage, name='logoutPage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('profile/', views.profile, name='profile_view'),
    path('change_password/', views.change_password, name='change_password'),
    path('passwordchangesuccess/',views.password_change_success,name='password_change_success'),
    path('passwordreset', views.password_reset, name='passwordreset'),
    path('passwordreset_next/<int:user_id>', views.password_reset_next, name='passwordresetnext'),
    path('add_security_questions/<int:user_id>', views.add_security_questions, name='add_security_questions'),
]

GreenConscious/MainPage/urls.py
from django.urls import path
from . import views

app_name = 'MainPage'

urlpatterns = [
    path('home/', views.main_page, name='main_page'),
    path('home/myevents/', views.myEvents, name='myevents'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event_update/<int:event_id>/', views.event_update, name='event_details_update'),
    path('past_events/', views.past_events, name='past_events'),  # Add this line
    path('event_delete/<int:event_id>/', views.event_delete, name='event_delete'),
    path('cancel_registration/<int:event_id>/', views.cancel_registration, name='cancel_registration'),
]

GreenConscious/Login_SignUp/models.py
from django.db import models
from django.contrib.auth.models import User
from MainPage.models import *


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=50, blank=False, null=False)
    country = models.CharField(max_length=50, blank=False, null=False)
    profileImage = models.ImageField(upload_to='profile-images/', default=None, blank=True, null=True)
    eventInterested = models.ForeignKey(EventCategory, on_delete=models.CASCADE, default=1)


class SecurityQuestion(models.Model):
    question_text = models.CharField(max_length=255)

    def __str__(self):
        return self.question_text


class SecurityAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(SecurityQuestion, on_delete=models.CASCADE)
    answer = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.user.username} - {self.question.question_text}"

GreenConscious/Login_SignUp/forms.py
#LoginForm
#SignUp Form
#Profile

from django import forms

from django.contrib.auth.models import User

from Login_SignUp.models import SecurityQuestion

from MainPage.models import EventCategory


class signupForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), label='Password', max_length=10)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        help_texts = {
            'username': None,
        }
        labels = {
            'username': 'Username',
            'email': 'Email',
            'password': 'Password'
        }


class loginForm(forms.Form):
    loginUserName = forms.CharField(max_length=50, label="Username")
    loginPassword = forms.CharField(widget=forms.PasswordInput(), label="Password")


class profileForm(forms.Form):
    userFirstName = forms.CharField(max_length=50, label="First Name", widget=forms.TextInput(attrs={'class': 'myProfileAttr'}))
    userLastName = forms.CharField(max_length=50, label="Last Name")
    userCity = forms.CharField(max_length=50, label="City")
    userCountry = forms.CharField(max_length=50, label="Country")
    userEventInterested = forms.ModelChoiceField(
        queryset=EventCategory.objects.all(),
        label='Events Interested',
        widget= forms.Select(attrs={'style': 'width:95%; height:35px; border: 1px solid #ccc;border-radius: 4px;'})
    )
    userProfileImage = forms.ImageField(required=False,
                                        label='Profile Image',
                                        widget=forms.ClearableFileInput())


class PasswordChangeForm(forms.Form):
    oldPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'input-group'}), label="Old Password")
    newPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'input-group'}), label="New Password")
    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'input-group'}), label="Confirm Password")


class ResetPasswordForm(forms.Form):
    userName = forms.CharField(max_length=50, label="Username")


class ResetPasswordNextForm(forms.Form):
    userName = forms.CharField(max_length=50, label="Username")
    newPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'input-group'}), label="New Password")
    confirmPassword = forms.CharField(widget=forms.PasswordInput(attrs={'class' : 'input-group'}), label="Confirm Password")
    answer = forms.CharField(max_length=255, label="Answer")
    question_id = forms.IntegerField(widget=forms.HiddenInput())


class SecurityQuestionForm(forms.Form):
    question1 = forms.ModelChoiceField(queryset=SecurityQuestion.objects.all(), label="Question 1")
    answer1 = forms.CharField(max_length=255, label="Answer 1")
    question2 = forms.ModelChoiceField(queryset=SecurityQuestion.objects.all(), label="Question 2")
    answer2 = forms.CharField(max_length=255, label="Answer 2")
    question3 = forms.ModelChoiceField(queryset=SecurityQuestion.objects.all(), label="Question 3")
    answer3 = forms.CharField(max_length=255, label="Answer 3")

GreenConscious/Login_SignUp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from Login_SignUp.forms import signupForm, loginForm, profileForm, PasswordChangeForm, ResetPasswordForm, \
    SecurityQuestionForm, ResetPasswordNextForm
from Login_SignUp.models import UserProfile, SecurityAnswer, SecurityQuestion
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
import random

from MainPage.models import EventCategory


def loginPage(request):
    if request.method == 'POST':
        form = loginForm(request.POST)
        if form.is_valid():
            userName = form.cleaned_data['loginUserName']
            userPassword = form.cleaned_data['loginPassword']
            try:
                checkUserName = User.objects.get(username=userName)
                user = authenticate(request, username=userName, password=userPassword)
                if user is not None:
                    login(request, user)
                    return redirect('MainPage:main_page')
                else:
                    return render(request, template_name='login.html', context={'form': form,
                                                                                'invalidMessage': 'Invalid Username/Password. Please try again'})
            except User.DoesNotExist:
                return render(request, template_name='login.html',
                              context={'form': form, 'invalidMessage': 'Invalid Username/Password. Please try again'})

        else:
            return render(request, template_name='login.html',
                          context={'form': form, 'invalidMessage': 'Unable to proceed. Please try again!'})
    else:
        form = loginForm()
        return render(request, template_name='login.html', context={'form': form, 'invalidMessage': ''})


def logoutPage(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, template_name='logout.html', context={})
    else:
        return redirect('Login_SignUp:homePage')


def signupPage(request):
    if request.method == 'POST':
        form = signupForm(request.POST)
        if form.is_valid():
            userName = form.cleaned_data['username']
            userEmail = form.cleaned_data['email']
            userPassword = form.cleaned_data['password']
            try:
                user = User.objects.create(username=userName, email=userEmail)
                user.set_password(userPassword)
                user.save()
                return redirect('Login_SignUp:add_security_questions', user_id=user.id)
            except Exception as exception:
                return HttpResponse(f'Signup failed: {exception}')
        else:
            return render(request, template_name='signup.html',
                          context={'form': form, 'invalidMessage': 'Unable to proceed. Please try again'})
    else:
        form = signupForm()
        return render(request, template_name='signup.html', context={'form': form})


def profile(request):
    if request.user.is_authenticated:
        inputUserName = request.user.username
        userDetails = User.objects.get(username=inputUserName)
        if request.method == 'POST':
            form = profileForm(request.POST, request.FILES)
            if form.is_valid():
                userFirstName = form.cleaned_data['userFirstName']
                userLastName = form.cleaned_data['userLastName']
                userCity = form.cleaned_data['userCity']
                userCountry = form.cleaned_data['userCountry']
                userEventInterested = form.cleaned_data['userEventInterested']
                userDetails.first_name = userFirstName
                userDetails.last_name = userLastName
                eventCategory = EventCategory.objects.get(name=userEventInterested)
                try:
                    userProfile = UserProfile.objects.get(user=userDetails)
                except UserProfile.DoesNotExist:
                    userProfile = None

                if userProfile is None:
                    userProfileImage = request.FILES['userProfileImage']
                    userProfile = UserProfile.objects.create(user=userDetails,
                                                             city=userCity, country=userCountry,
                                                             profileImage=userProfileImage,
                                                             eventInterested=eventCategory)
                    userDetails.save()
                    userProfile.save()
                else:
                    if 'userProfileImage-clear' in request.POST:
                        userProfile.profileImage.delete()
                        userProfile.profileImage = None
                    elif 'userProfileImage' in request.FILES:
                        userProfileImage = request.FILES['userProfileImage']
                        userProfile.profileImage.delete()
                        userProfile.profileImage = None
                        userProfile.profileImage = userProfileImage
                    userDetails.save()
                    userProfile.city=userCity
                    userProfile.country=userCountry
                    userProfile.eventInterested=eventCategory
                    userProfile.save()
                return redirect('MainPage:main_page')
        else:
            try:
                userprofile_details = UserProfile.objects.get(user=userDetails)
            except UserProfile.DoesNotExist:
                userprofile_details = None

            if userprofile_details is None:
                initial_data = {
                    'userFirstName': "",
                    'userLastName': "",
                    'userCity': "",
                    'userCountry': "",
                    'userEventInterested': "",
                    'userProfileImage': "",
                }
                form = profileForm(initial=initial_data)
            else:
                initial_data = {
                    'userFirstName': userprofile_details.user.first_name,
                    'userLastName': userprofile_details.user.last_name,
                    'userCity': userprofile_details.city,
                    'userCountry': userprofile_details.country,
                    'userEventInterested': EventCategory.objects.get(id=userprofile_details.eventInterested.id),
                    'userProfileImage': userprofile_details.profileImage
                }
                form = profileForm(initial=initial_data)
            context = {
                'form': form,
                'userDetails': userDetails,
                'userProfile': userprofile_details
            }
            return render(request, 'profile.html', context)
    else:
        return render(request, template_name='homepage.html', context={})


def change_password(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(request.POST)
            if form.is_valid():
                oldpassword = form.cleaned_data['oldPassword']
                newpassword = form.cleaned_data['newPassword']
                confirmpassword = form.cleaned_data['confirmPassword']
                user = authenticate(request, username=request.user.username, password=oldpassword)
                if user is not None:
                    if confirmpassword != newpassword:
                        return HttpResponse('Old password and new password did not match, Please try again')
                    else:
                        user.set_password(newpassword)
                        user.save()
                        return render(request, template_name="passwordchangesuccess.html", context={})
                else:
                    return HttpResponse('Incorrect old password, Please try again')
            else:
                return HttpResponse('Invalid Data, Please try again')
        else:
            form = PasswordChangeForm()
            return render(request, template_name='changepassword.html', context={'form': form})
    else:
        return redirect('Login_SignUp:homePage')


def homePage(request):
    return render(request, template_name='homepage.html', context={})


def password_change_success(request):
    if request.user.is_authenticated:
        return render(request, template_name='passwordchangesuccess.html', context={})
    else:
        return redirect('Login_SignUp:homePage')


def password_reset(request):
    if request.method == 'POST':
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['userName']
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                return HttpResponse('Incorrect username, Please try again')
            return redirect('Login_SignUp:passwordresetnext', user_id=user.id)
        else:
            return HttpResponse('Invalid Data, Please try again')
    else:
        form = ResetPasswordForm()
        return render(request, template_name='passwordreset.html', context={'form': form})


def password_reset_next(request, user_id):
    if request.method == 'POST':
        form = ResetPasswordNextForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['userName']
            question_id = form.cleaned_data['question_id']
            answer = form.cleaned_data['answer']

            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                return HttpResponse('Incorrect username, Please try again')

            try:
                security_answer = SecurityAnswer.objects.get(user=user, question_id=question_id)
                if security_answer.answer == answer:
                    # Perform password reset logic here

GreenConscious/Login_SignUp/templates/add_security_questions.html
{% extends 'base.html' %}

{% block title %}
    Add Security Questions
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Add Security Questions</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
{% endblock %}

GreenConscious/Login_SignUp/templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Change Password</title>
    <link rel="stylesheet" type="text/css" href="../../static/changepasswordstyle.css">
    <style>

        .navbar {
            background-color: #4CAF50;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
            height: 35px;
        }
        .navbar a {
            text-decoration: none;
        }

        .navbar .name {
            color: white;
            font-size: 30px;
            font-weight: bold;
            text-decoration: none;
        }

        .navbar .login-register a {
            text-decoration: none;
        }

        .navbar .login-register button {
            background-color: white;
            color: #4CAF50;
            border: none;
            padding: 10px 20px;
            margin: 0 5px;
            cursor: pointer;
            border-radius: 5px;
        }
        .navbar .login-register button:hover {
            background-color: #45a049;
            color: white;
        }

        .container {
            margin: 40px;
        }
    </style>

</head>
<body>
    <div class="navbar">
        <a href="{% url 'MainPage:main_page' %}">
            <div class="name">Green Conscious</div>
        </a>
        <div class="login-register">
            <a href="{% url 'Login_SignUp:profile_view' %}">
                <button>My Profile</button>
            </a>
            <a href="{% url 'Login_SignUp:logoutPage' %}">
                <button>Logout</button>
            </a>
        </div>
    </div>
    <div class="container">
        <h2>Change Password</h2>
        <form method="POST" action="{% url 'Login_SignUp:change_password' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Change Password</button>
        </form>
    </div>
</body>
</html>

GreenConscious/Login_SignUp/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Green Conscious - An Event Creation Site</title>

    <!-- Link CSS file -->
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="../../static/homepagestyle.css">
</head>
<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-success">
    <a class="navbar-brand text-white text_navbar" href="{% url 'Login_SignUp:homePage' %}">Green Conscious</a>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link nav_button text_navbar" href="{% url 'Login_SignUp:loginPage' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav_button text_navbar" href="{% url 'Login_SignUp:signupPage' %}">Sign Up</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Main Content -->
<div id="carouselExampleIndicators" class="carousel slide full-height" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="../../static/images/GreenConscious_Homepage_1.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../../static/images/GreenConscious_Homepage_2.png" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="../../static/images/GreenConscious_Homepage_3.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<script>
  const carousel = document.querySelector('.full-height');
  const navbarHeight = document.querySelector('.navbar').offsetHeight;

  function setCarouselHeight() {
    const windowHeight = window.innerHeight;
    carousel.style.height = `${windowHeight - navbarHeight}px`;
  }

  window.addEventListener('resize', setCarouselHeight);
  setCarouselHeight(); // Call it initially on page load
</script>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

GreenConscious/Login_SignUp/templates/login.html
{% extends 'login_base.html' %}
{% block title %}
    Green Conscious - Login
{% endblock %}

{% block body_content %}
<body class="login-body">
    <div class="navbar-heading">
        <a href="{% url 'MainPage:main_page' %}">
            <div class="name">Green Conscious</div>
        </a>
    </div>
    <div class="container">
        <h2>Login</h2>
        <form action="{% url 'Login_SignUp:loginPage' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Login</button>
        </form>
        <p>Don't have an account? <a href="{% url 'Login_SignUp:signupPage' %}">Sign up here</a></p>
        <p>Forgot Your Password? <a href="{% url 'Login_SignUp:passwordreset' %}">Reset Here</a></p>
        {% if invalidMessage %}
            <p style="color: red">{{ invalidMessage }}</p>
        {% endif %}
    </div>
</body>
{% endblock %}

GreenConscious/Login_SignUp/templates/login_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/login_signup_styles.css">
    <title>
        {% block title%}
        title_from_the_login_or_signup_page
        {% endblock %}
    </title>
    <style>
        .errorlist {
            color: red;
        }

        .navbar-heading {
            background-color: #4CAF50;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
            text-decoration: none;
            height: 35px;
        }

        .navbar-heading a {
            text-decoration: none;
        }

        .navbar-heading .name {
            color: white;
            font-size: 30px;
            font-weight: bold;
            text-decoration: none;
        }
    </style>
</head>

{% block body_content %}
{% endblock %}

</html>

GreenConscious/Login_SignUp/templates/logout.html
{% extends 'login_base.html' %}

{% block title %}
    Green Conscious - Logout
{% endblock %}


{% block body_content %}
    <body class="logout-body">
    <div class="container">
        <div class="message">
        <p>You have been logged out. You will be redirected to the home page shortly.</p>
        </div>
        <script>
            setTimeout(function() {
                window.location.href = "{% url 'Login_SignUp:homePage' %}";
            }, 2000);
        </script>
    </div>
    </body>
{% endblock %}

GreenConscious/Login_SignUp/templates/passwordchangesuccess.html
{% extends 'login_base.html' %}

{% block title %}
    Green Conscious - Password Change Success!!
{% endblock %}


{% block body_content %}
    <body class="logout-body">
    <div class="container">
        <div class="message">
        <p>Password is changed successfully. You will be redirected to the login page shortly.</p>
        </div>
        <script>
            setTimeout(function() {
                window.location.href = "{% url 'Login_SignUp:logoutPage' %}";
            }, 2000);
        </script>
    </div>
    </body>
{% endblock %}

GreenConscious/Login_SignUp/templates/passwordreset.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reset Password</title>
    <link rel="stylesheet" type="text/css" href="../../static/passwordresetstyle.css">
</head>
<body>
    <div class="container">
        <h2>Password Reset</h2>
        <form method="POST" action="{% url 'Login_SignUp:passwordreset' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="button">Change Password</button>
        </form>

    </div>
</body>
</html>

GreenConscious/Login_SignUp/templates/profile.html
<!-- profile.html -->
{% load static %}  <!-- Load static tag library -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Profile</title>
    <link rel="stylesheet" type="text/css" href="../../static/profilestyle.css">
    <style>
        .sidenav {
          height: 40%;
          width: 300px;
          position: fixed;
          z-index: 1;
          top: 0;
          left: 0;
          background-color: #81c784;
          overflow-x: hidden;
          padding-top: 20px;
          margin-top : 200px;
          margin-left : 20px;
          border-radius: 10px;
        }

        .sidenav a {
          padding: 15px;
          text-decoration: none;
          font-size: 25px;
          color: #555555;
          display: block;
        }

        .sidenav a:hover {
          color: #f1f1f1;
        }

        .navbar-heading {
            background-color: #4CAF50;
            padding: 10px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
            text-decoration: none;
            height: 35px;
        }

        .navbar-heading a {
            text-decoration: none;
        }

        .navbar-heading .name {
            color: white;
            font-size: 30px;
            font-weight: bold;
            text-decoration: none;
        }

        .button {
              display: inline-block;
              padding: 10px 5px;
              font-size: 14px;
              color: white;
              background-color: #4CAF50;
              text-align: center;
              text-decoration: none;
              border-radius: 3px;
              transition: background-color 0.3s;
            }

            .button:hover {
              background-color: #45a049;
            }
    </style>

</head>
<body>
    <div class="navbar-heading">
        <a href="{% url 'MainPage:main_page' %}">
            <div class="name">Green Conscious</div>
        </a>
    </div>
    <div class="sidenav">
          <a href="{% url 'MainPage:main_page' %}">Home</a>
          <a href="{% url 'MainPage:myevents' %}">My Events</a>
          <a href="{% url 'Login_SignUp:change_password' %}">Change Password</a>
        <a href="{% url 'Login_SignUp:logoutPage' %}">Logout</a>
    </div>

    <div class="container">
        <div class="container1">
            <div class="profile-heading">
                <h1>User Profile</h1>
                <p>Welcome, {{ userDetails.username }}</p>
                <p>Email: {{ userDetails.email }}</p>
            </div>
            <div class="profile-image">
                {% if userProfile %}
                    {% if userProfile.profileImage %}
                        <img src="{{ userProfile.profileImage.url }}" alt="Profile Image">
                    {% else %}
                        <img src="/media/profile-images/default-profile-photo.png" alt="Profile Image">
                    {% endif %}
                {% else %}
                        <img src="/media/profile-images/default-profile-photo.png" alt="Profile Image">
                {% endif %}

            </div>
        <a href="{% url 'user_history' %}" class="button">User History</a>
        </div>
        <div class="container2">
            <div class="profile-details">
                {% if userDetails %}
                    <form action="{% url 'Login_SignUp:profile_view'  %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Save Profile">
                    </form>
                {% else %}
                    <!-- Display form for the first time entry -->
                    <form action="{% url 'Login_SignUp:profile_view' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Create Profile">
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</body>
</html>

GreenConscious/Login_SignUp/templates/signup.html
{% extends 'login_base.html' %}

{% block title %}
    Green Conscious - Signup
{% endblock %}

{% block body_content %}
<body class="signup-body">
    <div class="navbar-heading">
        <a href="{% url 'MainPage:main_page' %}">
            <div class="name">Green Conscious</div>
        </a>
    </div>
    <div class="container">
        <h2>Sign Up</h2>
        <form action="{% url 'Login_SignUp:signupPage' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Sign Up</button>
        </form>
        <p>Already have an account? <a href="{% url 'Login_SignUp:loginPage' %}">Login here</a></p>
        {% if invalidMessage %}
            <p style="color: red">{{ invalidMessage }}</p>
        {% endif %}
    </div>
</body>
{% endblock %}