GreenConscious/About/urls.py
from django.urls import path
from .views import about_view

urlpatterns = [
    path('', about_view, name='about'),
]

GreenConscious/EventsPage/urls.py
from django.urls import path

import MainPage.views
from . import views

app_name = 'EventsPage'

urlpatterns = [
    path('', views.event_creation, name='event_creation'),
    path('event_creation/', views.event_creation, name='event_creation'),
    path('event_registration/<int:event_id>/', views.event_registration, name='event_registration'),
    path('main_page/', MainPage.views.main_page, name='main_page'),
]

GreenConscious/GreenConscious/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# Define URL patterns for each app
greenconscious_patterns = [
    path('', include('Login_SignUp.urls')),
    path('', include('MainPage.urls')),
    path('events/', include('EventsPage.urls')),
    path('community/', include('community.urls')),
    path('volunteer_matching/', include('VolunteerMatching.urls')),
    path('about/', include('About.urls')),
    path('contact/', include('Contact.urls')),
    path('', include('userhistory.urls')),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('greenconscious/', include(greenconscious_patterns)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GreenConscious/Login_SignUp/urls.py
from django.urls import path
from . import views

app_name = 'Login_SignUp'

urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('login/', views.loginPage,  name='loginPage'),
    path('logout/', views.logoutPage, name='logoutPage'),
    path('signup/', views.signupPage, name='signupPage'),
    path('profile/', views.profile, name='profile_view'),
    path('change_password/', views.change_password, name='change_password'),
    path('passwordchangesuccess/',views.password_change_success,name='password_change_success'),
    path('passwordreset', views.password_reset, name='passwordreset'),
    path('passwordreset_next/<int:user_id>', views.password_reset_next, name='passwordresetnext'),
    path('add_security_questions/<int:user_id>', views.add_security_questions, name='add_security_questions'),
]

GreenConscious/MainPage/urls.py
from django.urls import path
from . import views

app_name = 'MainPage'

urlpatterns = [
    path('home/', views.main_page, name='main_page'),
    path('home/myevents/', views.myEvents, name='myevents'),
    path('event/<int:event_id>/', views.event_detail, name='event_detail'),
    path('event_update/<int:event_id>/', views.event_update, name='event_details_update'),
    path('past_events/', views.past_events, name='past_events'),  # Add this line
    path('event_delete/<int:event_id>/', views.event_delete, name='event_delete'),
    path('cancel_registration/<int:event_id>/', views.cancel_registration, name='cancel_registration'),
]

GreenConscious/MainPage/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Event(models.Model):
    name = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='event_images/', null=True, blank=True)  # New field for event image
    location = models.CharField(max_length=255, default='Windsor, ON')
    category = models.ForeignKey('EventCategory', on_delete=models.CASCADE, related_name='events', default=1)

    def __str__(self):
        return self.name


class EventCategory(models.Model):
    name = models.CharField(max_length=100, blank=False, unique=True, null=False)
    #totalEvents = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    @property
    def total_events(self):
        return self.events.count()

GreenConscious/MainPage/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.models import User
from django.utils import timezone

from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from EventsPage.forms import EventCreationForm
from EventsPage.models import EventRegistration
from MainPage.models import Event, EventCategory
from django.db.models import Q
from django.http import HttpResponse


def parse_custom_date(date_str):
    try:
        # Attempting to parse the date string in the format "Month. Day, Year"
        return datetime.strptime(date_str, '%b. %d, %Y').date()
    except ValueError:
        return None


def main_page(request):
    if not request.user.is_authenticated:
        return redirect('Login_SignUp:homePage')
    query = request.GET.get('q')
    category_id = request.GET.get('category')
    events_list = Event.objects.all()

    # filter events
    if category_id:
        events_list = events_list.filter(category_id=category_id)

    if query:
        # Initially checking if the search input is a date or not
        query_date = parse_custom_date(query)
        if query_date:
            events_list = events_list.filter(Q(start_date=query_date) | Q(end_date=query_date))
        else:
            # If the search input isn't a date, filtering the date with event name
            events_list = events_list.filter(Q(name__icontains=query))

    # Paginator settings
    paginator = Paginator(events_list, 5)  # Show 10 events per page

    page = request.GET.get('page')
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        events = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        events = paginator.page(paginator.num_pages)

    categories = EventCategory.objects.all()  # Retrieve all event categories

    return render(request, 'MainPage/main_page.html', {'events': events,
                                                       'query': query,
                                                       'categories': categories,
                                                       'selected_category': int(category_id) if category_id else None
                                                       })


def event_detail(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    disable_flag = True
    event_creator_user_id = event.created_by.id

    if request.user.id == event_creator_user_id:
        disable_flag = False

    is_creator = event.created_by == request.user

    is_registered = EventRegistration.objects.filter(event=event, user=request.user).exists()

    register_flag = is_creator or is_registered

    return render(request, 'MainPage/event_detail.html',
                  {'event': event, 'disable_flag': disable_flag,
                   'register_flag': register_flag, 'is_registered': is_registered})


def past_events(request):
    events_list = Event.objects.filter(end_date__lt=timezone.now()).order_by('-end_date')

    # Paginator settings
    paginator = Paginator(events_list, 5)  # Show 5 events per page

    page = request.GET.get('page')
    try:
        events = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        events = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        events = paginator.page(paginator.num_pages)

    return render(request, 'MainPage/past_events.html', {'events': events})


def event_update(request, event_id):
    if not request.user.is_authenticated:
        return redirect('Login_SignUp:homePage')
    event = get_object_or_404(Event, id=event_id)
    if request.method == 'POST':
        form = EventCreationForm(request.POST, request.FILES)
        if form.is_valid():
            event.name = form.cleaned_data['event_name']
            event.start_date = form.cleaned_data['start_date']
            event.end_date = form.cleaned_data['end_date']
            event.description = form.cleaned_data['event_description']
            event.location = form.cleaned_data['location']
            event.category = form.cleaned_data['event_category']
            if 'image-clear' in request.POST:
                event.image.delete()
                event.image = None
            elif 'image' in request.FILES:
                event.image = request.FILES['image']
            event.save()

            return redirect('MainPage:event_detail', event_id=event.id)
        else:
            return render(request, 'MainPage/event_update.html', {'form': form,
                                                                  'given_event_id': event_id})
    else:
        form = EventCreationForm(initial={
            'event_name': event.name,
            'start_date': event.start_date,
            'end_date': event.end_date,
            'event_description': event.description,
            'location': event.location,
            'image': event.image,
            'event_category': event.category,
        })
        return render(request, 'MainPage/event_update.html', {'form': form,
                                                              'given_event_id': event_id})


def myEvents(request):
    if not request.user.is_authenticated:
        return redirect('Login_SignUp:homePage')
    display_type = request.GET.get('display', 'created')  # Default to 'created'

    events_to_display = False

    if display_type == 'registered':
        events_registered = Event.objects.filter(eventregistration__user=request.user)
        events_created = None
    else:
        events_created = Event.objects.all().filter(created_by=request.user)
        events_registered = None

    events_to_display = events_created or events_registered
    return render(request, template_name='MainPage/myevents.html', context={'events_to_display': events_to_display,
                                                                            'events_created': events_created,
                                                                            'events_registered': events_registered})


def event_delete(request, event_id):
    if not request.user.is_authenticated:
        return redirect('Login_SignUp:homePage')

    event = get_object_or_404(Event, id=event_id)
    disable_flag = True
    event_creator_user_id = event.created_by.id

    if request.user.id == event_creator_user_id:
        disable_flag = False

    if request.method == 'POST':
        event.delete()
        messages.success(request, "Event deleted successfully.")
        return redirect('MainPage:main_page')

    return render(request, 'MainPage/event_detail.html',
                  {'event': event, 'disable_flag': disable_flag})


def cancel_registration(request, event_id):
    if not request.user.is_authenticated:
        return redirect('Login_SignUp:homePage')

    event = get_object_or_404(Event, id=event_id)
    registration = get_object_or_404(EventRegistration, event=event, user=request.user)

    disable_flag = True
    event_creator_user_id = event.created_by.id

    if request.user.id == event_creator_user_id:
        disable_flag = False

    if request.method == 'POST':
        registration.delete()
        messages.success(request, "Event deleted successfully.")
        return redirect('MainPage:main_page')

    return render(request, 'MainPage/event_detail.html',
                  {'event': event, 'disable_flag': disable_flag})

GreenConscious/MainPage/templates/MainPage/event_detail.html
{% extends 'base.html' %}

{% block title %}Event Details{% endblock %}

{% load static %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'MainPage/style.css' %}">
    <style>
        .event-image {
            max-width: 100%;
            height: auto;
            border-radius: 5px;
            margin-bottom: 20px;
        }

        .back-button {
            display: inline-block;
            margin-top: 20px;
            background-color: #4CAF50;
            color: white;
            border: none;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            border-radius: 5px;
            transition-duration: 0.4s;
        }

        .back-button:hover {
            background-color: white;
            color: #4CAF50;
            border: 2px solid #4CAF50;
        }

        .disabled-btn {
            display: none;
        }

        /* Styling for event list */
        .event {
            margin-top: 85px !important;
            margin-bottom: 20px;
            /* border: 1px solid #ddd; */
            border-radius: 8px;
            padding: 15px;
            background-color: #f9f9f9;
        }

        .event-header {
            display: flex;
            align-items: center;
            margin-bottom: 10px;
        }

        .event-header img.profile-img {
            border-radius: 50%;
            width: 50px;
            height: 50px;
            object-fit: cover;
            margin-right: 10px;
        }

        .event-header .event-info {
            display: flex;
            justify-content: space-between;
            width: 100%;
        }

        .event-title {
            font-size: 1.2em;
            font-weight: bold;
        }

        .event-time {
            font-size: 0.9em;
            color: #555;
        }

        .event img {
            max-width: 100%;
            height: auto;
            border-radius: 8px;
            margin-top: 10px;
        }

        .container-fluid {
            display: flex !important;
            flex-direction: column !important;
            align-items: center !important;
            margin-top: 60px !important;
            min-height: 70vh !important;
        }

        .content {
            margin-top: 60px !important;
            padding: 0 !important;
            font-family: "Eras Medium ITC", sans-serif !important;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block navbar-content %}
    <a href="{% url 'MainPage:main_page' %}">
        <div class="name">Green Conscious</div>
    </a>
    <div class="login-register">
        <a href="{% url 'Login_SignUp:profile_view' %}">
            <button>My Profile</button>
        </a>
        <a href="{% url 'MainPage:main_page' %}">
            <button>Home</button>
        </a>
    </div>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        {% with event.created_by.userprofile.profileImage as profile_image %}
            <div class="event">
                <div class="event_detail_heading" style="margin-left: -2% !important;">Event Details</div>
                <div class="event-header">
                    {% if profile_image %}
                        <img src="{{ profile_image.url }}" alt="{{ event.created_by.username }}" class="profile-img">
                    {% else %}
                        <img src="{% static 'default-profile.jpg' %}" alt="Default Profile" class="profile-img">
                    {% endif %}
                    <div class="event-info">
                        <div class="event-title">{{ event.created_by.username }}</div>
                        <div class="event-time">{{ event.start_date }}</div>
                    </div>
                </div>
                <a class="event_title" href="{% url 'MainPage:event_detail' event.id %}">{{ event.name }}</a>
                <p><strong>Description:</strong> {{ event.description }}</p>
                {% if event.image %}
                    <img src="{{ event.image.url }}" alt="{{ event.name }}">
                {% endif %}
                <p><strong>Category:</strong> {{ event.category }}</p>
                <p><strong>Location:</strong> {{ event.location }}</p>
            </div>
        {% endwith %}
        <div style="margin-bottom: 20px">
            <a href="{% url 'MainPage:main_page' %}" class="btn btn-primary back-button">Back to Events</a>
            {% if disable_flag %}
                <a href="{% url 'MainPage:event_details_update' event_id=event.id %}"
                   class="btn btn-primary back-button disabled-btn"
                   style="margin-left: 10px">Edit Event Details</a>
                <form action="{% url 'MainPage:event_delete' event_id=event.id %}" method="post"
                      style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary back-button disabled-btn"
                            style="margin-left: 10px">Delete Event
                    </button>
                </form>
            {% else %}
                <a href="{% url 'MainPage:event_details_update' event_id=event.id %}"
                   class="btn btn-primary back-button"
                   style="margin-left: 10px">Edit Event Details</a>
                <form action="{% url 'MainPage:event_delete' event_id=event.id %}" method="post"
                      style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary back-button" id="delete-button"
                            style="margin-left: 10px">Delete Event
                    </button>
                </form>
            {% endif %}

            {% if register_flag %}
                <a href="{% url 'EventsPage:event_registration' event.id %}"
                   class="btn btn-primary back-button disabled-btn"
                   style="margin-left: 10px">Register</a>
            {% else %}
                <a href="{% url 'EventsPage:event_registration' event.id %}"
                   class="btn btn-primary back-button"
                   style="margin-left: 10px">Register</a>
            {% endif %}

            {% if is_registered %}
                <form action="{% url 'MainPage:cancel_registration' event.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary back-button"
                            style="margin-left: 10px" id="cancel-button">Cancel Registration
                    </button>
                </form>
            {% else %}
                <button class="btn btn-primary back-button disabled-btn" id="cancel-button" style="margin-left: 10px"
                        disabled>Cancel Registration
                </button>
            {% endif %}

        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            let deleteButton = document.getElementById('delete-button');
            let cancelButton = document.getElementById('cancel-button');

            if (deleteButton) {
                deleteButton.addEventListener('click', function (event) {
                    if (!confirm('Are you sure you want to delete this event?')) {
                        event.preventDefault(); // Prevents the default action (navigation to the delete URL)
                    }
                });
            }

            if (cancelButton) {
                cancelButton.addEventListener('click', function (event) {
                    if (!confirm('Are you sure you want to cancel your registration from this event?')) {
                        event.preventDefault(); // Prevents the default action (navigation to the delete URL)
                    }
                });
            }
        });
    </script>
{% endblock %}

GreenConscious/MainPage/templates/MainPage/event_update.html
{% extends 'base.html' %}

{% block title %}Event Update{% endblock %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% endblock %}
{% block navbar-content%}
    <a href="{% url 'MainPage:main_page' %}">
        <div class="name">Green Conscious</div>
    </a>
    <div class="login-register">
        <a href="{% url 'Login_SignUp:profile_view' %}">
            <button>My Profile</button>
        </a>
        <a href="{% url 'MainPage:main_page' %}">
            <button>Home</button>
        </a>
    </div>
{%  endblock %}


{% block content %}
    <div class="container-fluid background">
        <div class="content event_create_form">
            <div class="heading">Event Details Update</div>
            <form action="{% url 'MainPage:event_details_update' event_id=given_event_id%}" method="post" 
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn back_button">Update My Event Details</button>
                <a href="{% url 'MainPage:event_detail' event_id=given_event_id%}"
                   class="btn btn-primary back_button">Back to Event Details</a>
            </form>
            <br>

        </div>
    </div>
{% endblock %}

GreenConscious/MainPage/templates/MainPage/main_page.html
{% extends 'base.html' %}

{% block title %}Your Dashboard{% endblock %}

{% load static %}

{% block extra_css %}
<link rel="stylesheet" type="text/css" href="{% static 'MainPage/style.css' %}">
<style>
  * {
    box-sizing: border-box;
  }

  .container {
    width: 100%;
  }

  .left {
    width: 25%;
    padding: 10px;
    background-color: transparent;
    border-radius: 8px 0 0 8px;
    vertical-align: top; /* Align content to the top */
    /* position: sticky; */
    top: 0;
    height: fit-content; /* Ensure the column doesn't take the full height */
  }

  .right {
    width: 75%;
    padding: 10px;
    background-color: transparent;
    border-radius: 0 8px 8px 0;
    vertical-align: top; /* Align content to the top */
  }

  .left .search_button {
    width: 100%;
    display: block;
    margin-bottom: 10px; /* Space between buttons */
  }

  .no-events-message {
    text-align: center;
    margin-top: 20px;
    font-style: italic;
    color: #999;
  }

  /* Styling for event list */
  .event {
    margin-bottom: 20px;
    /* border: 1px solid #ddd; */
    border-radius: 8px;
    padding: 15px;
    background-color: transparent;
  }

  .event-header {
    display: flex;
    align-items: center;
    margin-bottom: 10px;
  }

  .event-header img.profile-img {
    border-radius: 50%;
    width: 50px;
    height: 50px;
    object-fit: cover;
    margin-right: 10px;
  }

  .event-header .event-info {
    display: flex;
    justify-content: space-between;
    width: 100%;
  }

  .event-title {
    font-size: 1.2em;
    font-weight: bold;
  }

  .event-time {
    font-size: 0.9em;
    color: #555;
  }

  .event img {
    max-width: 100%;
    height: auto;
    border-radius: 8px;
    margin-top: 10px;
  }

  .pagination {
    margin-top: 20px;
  }

  .pagination .step-links a {
    margin: 0 5px;
  }

  .pagination .current {
    margin: 0 5px;
  }

  table {
      border-radius: 8px;
      box-shadow: 0 4px 16px rgba(0, 0, 0, 0.5);
  }
</style>
{% endblock %}

{% block navbar-content %}
    <a href="{% url 'MainPage:main_page' %}">
        <div class="name">Green Conscious</div>
    </a>
    <div class="login-register">
        <a href="{% url 'Login_SignUp:profile_view' %}">
            <button>My Profile</button>
        </a>
        <a href="{% url 'Login_SignUp:logoutPage' %}">
            <button>Log Out</button>
        </a>
    </div>
{% endblock %}

{% block content %}
<div class="container main">
  <table style="width: 100%; border-spacing: 20px;">
    <tr>
      <td class="left">
        <button onclick="location.href='{% url 'EventsPage:event_creation' %}'" class="search_button text-center">Create Event</button>
        <button onclick="location.href='{% url 'MainPage:main_page' %}'" class="search_button text-center">Upcoming Events</button>
        <button onclick="location.href='{% url 'MainPage:past_events' %}'" class="search_button text-center">Past Events</button>
        <button onclick="location.href='{% url 'volunteer_matching' %}'" class="search_button text-center">Find events you'd like</button>
        <button onclick="location.href='{% url 'community_page' %}'" class="search_button text-center">Community</button>
      </td>

      <td class="right">
        <form method="get" action="{% url 'MainPage:main_page' %}" class="search-form">
          <input type="text" name="q" class="input_field"
                 value="{% if query %}{{ query }}{% endif %}" title="Please enter Event Name or Date Mon. DD, YYYY"
                 placeholder="Search to filter">
          <select name="category" class="input_field">
            <option value="">All Categories</option>
            {% for category in categories %}
              <option value="{{ category.id }}"
                      {% if selected_category == category.id %}
                          selected
                      {% endif %}>
                {{ category.name }}
              </option>
            {% endfor %}
          </select>
          <button class="search_button text-center" type="submit">Search</button>
        </form>

        {% if events %}
          {% for event in events %}
            {% with event.created_by.userprofile.profileImage as profile_image %}
            <div class="event">
              <div class="event-header">
                {% if profile_image %}
                  <img src="{{ profile_image.url }}" alt="{{ event.created_by.username }}" class="profile-img">
                {% else %}
                  <img src="{% static 'default-profile.jpg' %}" alt="Default Profile" class="profile-img">
                {% endif %}
                <div class="event-info">
                  <div class="event-title">{{ event.created_by.username }}</div>
                  <div class="event-time">{{ event.start_date }}</div>
                </div>
              </div>
              <a class="event_title" href="{% url 'MainPage:event_detail' event.id %}">{{ event.name }}</a>
              <p><strong>Description:</strong> {{ event.description }}</p>
              {% if event.image %}
                <img src="{{ event.image.url }}" alt="{{ event.name }}">
              {% endif %}
              <p><strong>Category:</strong> {{ event.category }}</p>
              <p><strong>Location:</strong> {{ event.location }}</p>
            </div>
            {% endwith %}
          {% endfor %}

          <!-- Pagination links -->
          <div class="pagination">
            <span class="step-links">
              {% if events.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ events.previous_page_number }}">previous</a>
              {% endif %}

              <span class="current">
                Page {{ events.number }} of {{ events.paginator.num_pages }}.
              </span>

              {% if events.has_next %}
                <a href="?page={{ events.next_page_number }}">next</a>
                <a href="?page={{ events.paginator.num_pages }}">last &raquo;</a>
              {% endif %}
            </span>
          </div>
        {% else %}
          <p class="no-events-message">No events found.</p>
        {% endif %}
      </td>
    </tr>
  </table>
</div>
{% endblock %}